package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val label: String, val flag: String) {
    ENGLISH("en", "English", "EN"),
    NEPALI("ne", "नेपाली", "नेपाली")
}

data class AetStrings(
    val language: AppLanguage,
    val appTitle: String,
    val appSubtitle: String,
    val admin: String,
    val member: String,
    val login: String,
    val logout: String,
    val switchLanguage: String,

    // Bottom Navigation Tabs
    val tabDashboard: String,
    val tabLoans: String,
    val tabPassbook: String,
    val tabCommittee: String,
    val tabTreasury: String,
    val tabMembers: String,
    val tabLoanDesk: String,
    val tabReports: String,

    // Public Ledger Treasury
    val publicLedger: String,
    val transparentFinancialOverview: String,
    val bankLiquidity: String,
    val netLiquidInTreasury: String,
    val activeMembersLabel: String,
    val activeLoansLabel: String,
    val totalContributions: String,
    val totalContributionsSub: String,
    val activeLoansDeployed: String,
    val activeLoansSub: String,
    val loanInterestEarned: String,
    val loanInterestSub: String,
    val finesExtraIncome: String,
    val finesExtraSub: String,
    val payoutsDisbursed: String,
    val payoutsDisbursedSub: String,
    val addFineOrFee: String,

    // Member Dashboard
    val profileAddress: String,
    val totalContributed: String,
    val monthlyContribution: String,
    val currentMonthDue: String,
    val paid: String,
    val pending: String,
    val cleared: String,
    val payoutTurnLabel: String,
    val payoutReceived: String,
    val payoutSlated: String,
    val payMonthlyDues: String,
    val applyLoan: String,
    val viewPassbook: String,
    val interestPaid: String,
    val finesPaid: String,
    val activeLoansHeader: String,
    val nextQuarterlyDue: String,
    val payInterestAction: String,
    val repayPrincipalAction: String,

    // Admin Screens
    val committeeRoster: String,
    val adminFullAccessSub: String,
    val addMember: String,
    val editMember: String,
    val deleteMember: String,
    val markPending: String,
    val recordPaidBtn: String,
    val addFineBtn: String,
    val disbursePayoutBtn: String,
    val loanDeskTitle: String,
    val loanDeskSub: String,
    val principalRemaining: String,
    val annualRate: String,
    val quarterlyInterest: String,
    val purpose: String,
    val approveAndDisburse: String,
    val rejectLoan: String,
    val editLoan: String,

    // Auth Screen
    val selectAccountTitle: String,
    val passcodePrompt: String,
    val directLoginTitle: String,
    val enterOtp: String,
    val verifyAndLogin: String,

    // Common Actions
    val cancel: String,
    val save: String,
    val confirm: String,
    val close: String,
    val all: String,
    val notifications: String,
    val cloudSync: String,
    val darkMode: String
)

val EnglishStrings = AetStrings(
    language = AppLanguage.ENGLISH,
    appTitle = "ADVANCE EDUCATIONAL TEAM",
    appSubtitle = "-AET since 2082 • 9-Member Committee",
    admin = "ADMIN",
    member = "MEMBER",
    login = "Login",
    logout = "Logout",
    switchLanguage = "Language",

    tabDashboard = "Dashboard",
    tabLoans = "Loans (10%)",
    tabPassbook = "Passbook",
    tabCommittee = "Committee",
    tabTreasury = "Treasury",
    tabMembers = "Members",
    tabLoanDesk = "Loan Desk",
    tabReports = "Reports",

    publicLedger = "Public Treasury Ledger",
    transparentFinancialOverview = "All-Member Transparent Financial Overview",
    bankLiquidity = "AET Bank / Cash Balance",
    netLiquidInTreasury = "Net Liquid Cash in Treasury Account",
    activeMembersLabel = "Members",
    activeLoansLabel = "Active Loans",
    totalContributions = "Total Pool Contributions",
    totalContributionsSub = "All members accumulated savings",
    activeLoansDeployed = "Active Loans Deployed",
    activeLoansSub = "Current active loan capital",
    loanInterestEarned = "Loan Interest Earned (10%)",
    loanInterestSub = "10% annual yield collected",
    finesExtraIncome = "Fines & Extra Income",
    finesExtraSub = "Late fees & penalty fund",
    payoutsDisbursed = "Payouts Disbursed",
    payoutsDisbursedSub = "Member rotation fund distributed",
    addFineOrFee = "Add Fine / Fee",

    profileAddress = "Address",
    totalContributed = "Total Contributed",
    monthlyContribution = "Monthly Savings",
    currentMonthDue = "Current Month Due",
    paid = "PAID",
    pending = "PENDING",
    cleared = "Cleared",
    payoutTurnLabel = "Turn Month",
    payoutReceived = "Paid (₹45,000)",
    payoutSlated = "Turn Slated",
    payMonthlyDues = "Pay Monthly Dues (₹5,000)",
    applyLoan = "Apply for Loan (10% p.a.)",
    viewPassbook = "View Passbook & Ledger",
    interestPaid = "Interest Paid",
    finesPaid = "Fines Paid",
    activeLoansHeader = "Active Loan (10% Annual Interest)",
    nextQuarterlyDue = "3-Month Interest Due",
    payInterestAction = "Pay Interest",
    repayPrincipalAction = "Repay Principal",

    committeeRoster = "Committee Member Roster",
    adminFullAccessSub = "Admin Full Access • 9 Committee Members",
    addMember = "Add Member",
    editMember = "Edit Details",
    deleteMember = "Delete Member",
    markPending = "Mark Pending",
    recordPaidBtn = "Record Paid",
    addFineBtn = "Add Fine",
    disbursePayoutBtn = "Payout ₹45K",
    loanDeskTitle = "Loan Portfolio & Approvals Desk",
    loanDeskSub = "Interest: 10% per year • 3-Month Cycle • Admin Full Access",
    principalRemaining = "Principal Remaining",
    annualRate = "Annual Rate (p.a.)",
    quarterlyInterest = "Quarterly Interest",
    purpose = "Purpose",
    approveAndDisburse = "Approve & Disburse",
    rejectLoan = "Reject",
    editLoan = "Edit",

    selectAccountTitle = "Select Your Committee Account",
    passcodePrompt = "Enter 4-Digit Passcode",
    directLoginTitle = "Quick Demo / One-Tap Access",
    enterOtp = "Enter 6-Digit OTP",
    verifyAndLogin = "Verify & Login",

    cancel = "Cancel",
    save = "Save Changes",
    confirm = "Confirm",
    close = "Close",
    all = "All",
    notifications = "Alerts & Notifications",
    cloudSync = "Sync to Firestore",
    darkMode = "Toggle Theme"
)

val NepaliStrings = AetStrings(
    language = AppLanguage.NEPALI,
    appTitle = "ADVANCE EDUCATIONAL TEAM",
    appSubtitle = "-AET since 2082 • ९ सदस्यीय समिति",
    admin = "प्रशासक (ADMIN)",
    member = "सदस्य (MEMBER)",
    login = "लगइन",
    logout = "लगआउट",
    switchLanguage = "भाषा (Language)",

    tabDashboard = "ड्यासबोर्ड",
    tabLoans = "ऋण (१०%)",
    tabPassbook = "पासबुक",
    tabCommittee = "समिति",
    tabTreasury = "कोष खाता",
    tabMembers = "सदस्यहरू",
    tabLoanDesk = "ऋण डेस्क",
    tabReports = "प्रतिवेदन",

    publicLedger = "सार्वजनिक कोष खाता (AET Ledger)",
    transparentFinancialOverview = "सबै सदस्यहरूको लागि पारदर्शी वित्तीय विवरण",
    bankLiquidity = "AET बैंक तथा नगद मौज्दात",
    netLiquidInTreasury = "कोषमा बाँकी रहेको शुद्ध मौज्दात रकम",
    activeMembersLabel = "सदस्यहरू",
    activeLoansLabel = "चालु ऋणहरू",
    totalContributions = "कुल जम्मा रकम",
    totalContributionsSub = "सबै सदस्यहरूको कुल बचत रकम",
    activeLoansDeployed = "लगानीमा रहेको ऋण",
    activeLoansSub = "सदस्यहरूमा चालु ऋण लगानी",
    loanInterestEarned = "ऋणबाट आर्जित ब्याज (१०%)",
    loanInterestSub = "वार्षिक १०% ब्याजबाट कोष आम्दानी",
    finesExtraIncome = "जरिवाना तथा अतिरिक्त आम्दानी",
    finesExtraSub = "विलम्ब शुल्क र दण्ड जरिवाना",
    payoutsDisbursed = "वितरण गरिएको पालो रकम",
    payoutsDisbursedSub = "सदस्यहरूलाई भुक्तानी भएको पालो रकम",
    addFineOrFee = "जरिवाना / शुल्क थप्नुहोस्",

    profileAddress = "ठेगाना",
    totalContributed = "कुल जम्मा योगदान",
    monthlyContribution = "मासिक बचत रकम",
    currentMonthDue = "चालु महिनाको किस्ता",
    paid = "चुक्ता",
    pending = "बाँकी",
    cleared = "भुक्तान भइसकेको",
    payoutTurnLabel = "पालो महिना",
    payoutReceived = "पालो प्राप्त (रु ४५,०००)",
    payoutSlated = "पालो आउन बाँकी",
    payMonthlyDues = "मासिक किस्ता बुझाउनुहोस् (रु ५,०००)",
    applyLoan = "ऋणको लागि निवेदन दिनुहोस् (१०%)",
    viewPassbook = "पासबुक तथा खाता विवरण हेर्नुहोस्",
    interestPaid = "बुझाइएको ब्याज",
    finesPaid = "बुझाइएको जरिवाना",
    activeLoansHeader = "चालु ऋण (वार्षिक १०% ब्याजदर)",
    nextQuarterlyDue = "३ महिनाको ब्याज भुक्तानी मिति",
    payInterestAction = "ब्याज बुझाउनुहोस्",
    repayPrincipalAction = "साँवा फिर्ता गर्नुहोस्",

    committeeRoster = "समिति सदस्य नामावली",
    adminFullAccessSub = "प्रशासक पूर्ण पहुँच • ९ समिति सदस्यहरू",
    addMember = "नयाँ सदस्य थप्नुहोस्",
    editMember = "विवरण सम्पादन",
    deleteMember = "सदस्य हटाउनुहोस्",
    markPending = "बाँकी राख्नुहोस्",
    recordPaidBtn = "रकम बुझाइयो",
    addFineBtn = "जरिवाना लगाउनुहोस्",
    disbursePayoutBtn = "पालो रु ४५,००० दिनुहोस्",
    loanDeskTitle = "ऋण व्यवस्थापन तथा स्वीकृति डेस्क",
    loanDeskSub = "ब्याज: वार्षिक १०% • ३ महिने चक्र • प्रशासक पूर्ण नियन्त्रण",
    principalRemaining = "बाँकी साँवा रकम",
    annualRate = "वार्षिक ब्याज दर",
    quarterlyInterest = "त्रैमासिक ब्याज रकम",
    purpose = "ऋणको प्रयोजन",
    approveAndDisburse = "स्वीकृत तथा भुक्तानी",
    rejectLoan = "अस्वीकृत",
    editLoan = "सम्पादन",

    selectAccountTitle = "आफ्नो समिति खाता छान्नुहोस्",
    passcodePrompt = "४-अङ्कको गोप्य पासवर्ड राख्नुहोस्",
    directLoginTitle = "द्रुत लगइन / एक क्लिक पहुँच",
    enterOtp = "६-अङ्कको OTP राख्नुहोस्",
    verifyAndLogin = "प्रमाणित गरि लगइन गर्नुहोस्",

    cancel = "रद्द गर्नुहोस्",
    save = "सुरक्षित गर्नुहोस्",
    confirm = "निश्चित गर्नुहोस्",
    close = "बन्द गर्नुहोस्",
    all = "सबै",
    notifications = "सूचना तथा अलर्टहरू",
    cloudSync = "क्लाउड सिंक",
    darkMode = "रंग थिम (Dark/Light)"
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

@Composable
fun getStrings(language: AppLanguage): AetStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.NEPALI -> NepaliStrings
    }
}
